Introduce `DiagnosticsError` and `ensure_diagnostics`
This allows catching the `Compilation failed.` error in more machine-friendly way, by using `anyhow::Error::downcast_ref` function.

commit-id:ce5928a4