Update package.json
VSCode with prettier fails to compile,

Prettier requires typescript v4.2.0+,
3.1.4 -> 4.2.0
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prettier/index.d.ts#L13

@types/node updated to 14 (oldest version with security support)
Version 8 -> 14
> ```error TS2694: Namespace 'NodeJS' has no exported member 'TypedArray'```